version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=wms
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3307
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
      - mysql

  web:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_USER: ivan
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_NAME: wms
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: bash -c "npm install && npm run migrations:run"
