version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=wms
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres

  web:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_USER: ivan
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_NAME: wms
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: bash -c "npm install && npm run migrations:run && npm start"

  web-local:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_USER: ivan
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_NAME: wms
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: bash -c "npm install && npm start"
